services:
  odoo:
    image: odoo:17
    environment:
      - SERVICE_FQDN_ODOO_8069
      - HOST=postgresql
      - USER=$SERVICE_USER_POSTGRES
      - PASSWORD=$SERVICE_PASSWORD_POSTGRES
    volumes:
      - odoo-web-data:/var/lib/odoo
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8069"]
      interval: 2s
      timeout: 10s
      retries: 30
  postgresql:
    image: postgres:16-alpine
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=$SERVICE_USER_POSTGRES
      - POSTGRES_PASSWORD=$SERVICE_PASSWORD_POSTGRES
      - POSTGRES_DB=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d postgres"]
      interval: 5s
      timeout: 20s
      retries: 10
